services:
  webserver:
    build:
      context: "services/webserver"
      dockerfile: "version/${PHP_VERSION}.Dockerfile"
      args:
        uid: "${PHP_UID}"
    image: "${PROJECT}_webserver:${PHP_VERSION}"
    container_name: "${PROJECT}_webserver"
    ports:
      - "${SERVICE_PORT}:80"
    volumes:
      # Log
      - "${STACK_DIR}/logs/nginx:/var/log/nginx"
      # Nginx
      - "${STACK_DIR}/.docker/services/webserver/config/nginx/http.d:/etc/nginx/http.d:ro"
      # PHP
      - "${STACK_DIR}/.docker/services/webserver/config/php/conf.d/php.ini:/usr/local/etc/php/conf.d/zz-gdrcd.ini:ro"
      - "${STACK_DIR}/.docker/services/webserver/config/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro"
      # Web
      - "${STACK_DIR}/www:/var/www/html"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      database:
        condition: service_healthy

  database:
    build:
      context: "services/database"
    image: "${PROJECT}_database"
    container_name: "${PROJECT}_database"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - "${STACK_DIR}/.docker/services/database/config/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "database-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p\"$$MYSQL_ROOT_PASSWORD\" --silent"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 60s

  phpmyadmin:
    build:
      context: "services/phpmyadmin"
    image: "${PROJECT}_phpmyadmin"
    container_name: "${PROJECT}_phpmyadmin"
    ports:
      - "${PMA_PORT}:80"
    environment:
      - PMA_HOST=database
      - UPLOAD_LIMIT=64M
    depends_on:
      database:
        condition: service_healthy
    profiles: ["phpmyadmin"]

  mailhog:
    build:
      context: "services/mailhog"
    image: "${PROJECT}_mailhog"
    container_name: "${PROJECT}_mailhog"
    ports:
      - "${MAILHOG_PORT}:8025"
    profiles: ["mailhog"]

# Volumes
volumes:
  database-data:

# Networks
networks:
  default:
    name: "${PROJECT}_network"
    external: true